### ISSUE TITLE
get_lldp_neighbors[detail] returns empty dict

### ISSUE THREAD

**Issue by egr3s** [napalm-automation-community/napalm-srlinux#13]
Hi,
I have a 7220 D3 box with v21.6.4 SW and the latest napalm-srlinux module.
I'm trying to fetch lldp neighbors, but it returns empty dict, although there are a few neighbors visible from the CLI and even via gnmic.

get_facts works fine, so it doesn't seem like a coding issue.

Code:
`

    driver = get_network_driver("srl")

    srl_args = {
        "gnmi_port": 57400,
        "jsonrpc_port": 443,
        "target_name": "<addr>",
        "tls_cert":f"{certs_path}/client.pem",
        "tls_ca": f"{certs_path}/ca.pem",
        "tls_key": f"{certs_path}/client-key.pem",
        "skip_verify": True,
        "insecure": True,
        "encoding": "JSON_IETF"
    } 

    device = driver("<addr>", user, pass, 60, srl_args)
    device.open()
    print("LLDP:", device.get_lldp_neighbors())
    device.close()
`

**Comment by egr3s** [comment]
Not sure which SRL OS version this library was tested with, but on my 21.6.4 the schema is different apparently. `get_lldp_neighbors` is looking for a `chassis_id` in the top level dict and cannot find it there. 
It starts working after removing the check for empty chassis_id [here](https://github.com/napalm-automation-community/napalm-srlinux/blob/8b7f5359ad87605bd1c2a5d311c83992efdf28c8/napalm_srl/srl.py#L1284).

**Comment by jbemmel** [comment]
Just tested on 'os_version': 'v22.6.4-90-g4b19af2d95' (container image) and it works for me on the latest main branch, using both lldp methods
