### ISSUE TITLE
Too old ansible requirements

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-srlinux#14]
Ansible 2.9.12 is quite old, is there any reason why requiring this version ? - https://github.com/napalm-automation-community/napalm-srlinux/blob/main/requirements.txt#L2

Also what's the reason for raising AnsibleConnectionFailure when failed to read certificate files? - https://github.com/napalm-automation-community/napalm-srlinux/blob/main/napalm_srl/srl.py#L2552
This is a napalm driver so I don't think it needs to be used together with ansible, so I don't understand why ansible exception. Napalm has its own set of [exceptions](https://github.com/Mellanox/napalm/blob/master/napalm/base/exceptions.py) so why not to use that? or a python standard exception?

@jbemmel I'm happy to raise a PR for this, just wants to know if it's fine to remove the ansible requirement.

**Comment by jbemmel** [comment]
Hi Marek,
See https://github.com/jbemmel/napalm-srlinux/commit/9c59f0e44d8e2eb1c3486345458ce622517ec3a1 - I had noticed the same, but hadn't come round to contributing (and testing) it

PR would be appreciated!

Thanks,
Jeroen

**Comment by omron93** [comment]
Great, thanks. Please review the PR #15 , that works for me
