### ISSUE TITLE
clarity on behaviour of load_replace_candidate

### ISSUE THREAD

**Issue by pyvkd** [napalm-automation-community/napalm-srlinux#19]
From the mapping documentation https://github.com/napalm-automation-community/napalm-srlinux/blob/main/Summary_of_Methods.pdf in section 2.6 about ```load_replace_config``` it says the follwoing:

```
Limitation
This method has implicit commit, when using this command user needs to be careful since the candidate config will be merged with running config along without an explicit commit. Numeric value for the position in the list of the change, and not the ID of the object. The ID of the object is stored as a separate leaf object in the SRL OS Yang models.
```

When going through the code https://github.com/napalm-automation-community/napalm-srlinux/blob/main/napalm_srl/srl.py#L2346 it doesn't suggest that there is any commit happening.

Can you please clarify what is the default behaviour here.

**Comment by jbemmel** [comment]
I believe that comment is misplaced - ```load_replace_config``` prepares a temporary config file on disk, the user is expected to call ```commit_config``` to apply the new configuration. The latter uses gRPC SET which commits the config. While it is true that gRPC SET uses implicit commit, the whole flow is fairly explicit imho, given the method's name
