### ISSUE TITLE
Rewrite gnmi code to use pyGnmi library

### ISSUE THREAD

**Issue by jbemmel** [napalm-automation-community/napalm-srlinux#26]
The generated protobuf files are getting old, which may lead to issues: https://github.com/napalm-automation-community/napalm-srlinux/pull/17

It would be better to rewrite the plugin to use pyGnmi for gNMI protocol interactions, such that we can lift along with updated versions as they come out

**Comment by tardoe** [comment]
In working on v2, we're removed the need for gNMI and are pulling details exclusively over JSONRPC. This allowed us to pull the gpb2.py and other infrastructure related to gNMI.
