### ISSUE TITLE
JSON diff not working

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-srlinux#27]
I'm using this driver to get running config (`get_config()` function) and then later I'm using the obtained config file to check that nothing changed on the device (`load_replace_candidate()` and `compare_config()` functions).

Despite the diff should be empty, the compare_config returns quite long diff.

**Comment by omron93** [comment]
@jbemmel Could you please check if you can reproduce the issue?
We get this issue with containerlab image. I wasn't testing this with physical device

**Comment by jbemmel** [comment]
```
from napalm import get_network_driver
import json

driver = get_network_driver("srl")
optional_args = {
    "gnmi_port": 57400,
    "jsonrpc_port": 80,
    "target_name": "clab-evpn-r1",
    "tls_ca": "/home/jeroen/srlinux/netlab/tests/clab-evpn/ca/root/root-ca.pem",
    "encoding": "JSON_IETF"
}
device = driver("192.168.121.101", "admin", "NokiaSrl1!", 60, optional_args)
device.open()
config = device.get_config()
print(config)
reply = device.load_replace_candidate(config=config["running"]) # JSON format
print( reply )
reply2 = device.commit_config()
print( reply2 )

# Diff should be empty
reply3 = device.compare_config()
print( "Diff: " + reply3 )

device.close()
```

Ran the above test, the returned diff is empty. Is this what you were doing?

**Comment by jbemmel** [comment]
Leaving out 'commit_config' caused an issue - fixed in PR https://github.com/napalm-automation-community/napalm-srlinux/pull/31
