### ISSUE TITLE
No way to update startup config

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-srlinux#47]
Is there a way to update startup config using this napalm driver? So in case the device reboots, the config stays the same
If this is not possible with current implementation, could this please be added?

I believe for example with Juniper napalm driver, the startup config gets updated when `commit_config()` operation is done.

**Comment by jbemmel** [comment]
Try setting that new `commit_save` flag and see if that works for you?

**Comment by jbemmel** [comment]
PR merged
