### ISSUE TITLE
Confusing driver name

### ISSUE THREAD

**Issue by jbemmel** [napalm-automation-community/napalm-srlinux#7]
https://github.com/napalm-automation-community/napalm-srlinux/blob/8b7f5359ad87605bd1c2a5d311c83992efdf28c8/setup.py#L11

With the repo being called napalm-srlinux, it is confusing to have the driver be called 'napalm-srl'

Consider https://www.python.org/dev/peps/pep-0423/#how-to-rename-a-project

**Comment by tardoe** [comment]
In working on v2, we've renamed the driver to `napalm-srlinux`.
