### ISSUE TITLE
grpc dependency greatly increases size of Netbox container image (compared to community version)

### ISSUE THREAD

**Issue by jbemmel** [napalm-automation-community/napalm-srlinux#8]
https://github.com/napalm-automation-community/napalm-srlinux/blob/8b7f5359ad87605bd1c2a5d311c83992efdf28c8/requirements.txt#L15

I built a Netbox container with support for both the SROS and SRLinux NAPALM drivers. It nearly doubled in size, compared to the original (728MB versus 446MB originally)

It may make more sense to also use Netconf towards SRLinux, perhaps even using a single harmonized driver.

**Comment by tardoe** [comment]
v2 aims to remove the need for GRPC libraries, this should be much more efficient with v2. We'll make sure to test Netbox support for v2.
